name: CI 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Check out Repo 
          uses: actions/checkout@v2
          with:
            repository: ${{ github.repository }}
        - name: verify directory
          run: ls
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: verify directory
          run: ls
       - name: Login to DockerHub
        uses: docker/login-action@v1 
          with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        - name: verify directory
          run: ls
        - name: Build 
          run: |
           ls && docker build --rm=false . --file Dockerfile --tag catch3_gtest_image_automate:1  && ls 
          
        - name: run
          run: ls && docker run "catch3_gtest_image_automate:1" /bin/bash && cd Catch2_testing && ls && cmake -Bbuild -H. -DBUILD_TESTING=OFF && sudo cmake --build build/ --target install && cd examples && g++ 020-TestCase-1.cpp && ./a.out
          
